language: go

go:
  - 1.8

node_js:
  - "6"
  - "node"

before_install:
  - npm install -g n
  - n 6.5.0
  - npm install collar-dev-server

script:
  - collar-dev-server
  - go test -cover

notifications:
  email:
    recipients:
      - daily.bhou@gmail.com
    on_success: change
    on_failure: always
